### ISSUE TITLE
مشکل کلمات کلیدی

### ISSUE THREAD

**Issue by Gitareschoob** [mjebrahimi/DNZ.SEOChecker#28]
سلام کلمات کلیدی من لیستی از رشته هست
وقتی رشته را به کیبورد میدم میگه کلمات استفاده نشده وقتی فقط یکی از کیبورد هارا از لیست بهش میدم درست میشه.
چجوری میشه لیست کیبورد را بهش بدی تا همه را چک کنه؟

**Comment by mjebrahimi** [comment]
سلام، این کامپوننت برای صرفا یک کلمه کلیدی طراحی شده و نمیتونه لیستی از کلمات رو به عنوان کلیدی بگیره.

برای اینکار باید سورسش رو خودتون کاستومایز کنین
